import { formatLockDuration, formatMultiplier, formatToken, glyphModel, type Pool } from "@forma/sdk";
import type { ReactNode } from "react";

import { GlyphMarks } from "./PositionGlyph";

const INK = "#0e1a2b";
const IVORY = "#f3efe4";
const MONO = "var(--font-plex-mono), ui-monospace, SFMono-Regular, Menlo, monospace";

/**
 * Pre-mint preview of the Position NFT. Mirrors the on-chain `PositionRenderer` SVG layout (same 400×400 frame,
 * header, glyph geometry and footer rows) but is filled only with the selected pool's real terms and the user's
 * input. It is labelled as a preview; nothing is minted until the stake transaction is confirmed.
 */
export function PositionPreviewCard({
  pool,
  expectedId,
  amount,
  now,
  rewardState,
}: {
  pool: Pool | undefined;
  expectedId: bigint | undefined;
  amount: bigint | undefined;
  now: bigint;
  rewardState: ReactNode;
}) {
  if (!pool) {
    return (
      <div className="border border-ink bg-paper p-5">
        <p className="label">Position NFT · preview</p>
        <div className="my-4 flex aspect-square w-full items-center justify-center border border-dashed border-rule-strong">
          <span className="label">Awaiting terms</span>
        </div>
        <p className="text-sm text-ink-2">Choose a lock tier to preview the position this stake would mint.</p>
      </div>
    );
  }

  const lock = pool.lockDuration;
  const id = expectedId ?? 0n;
  const g = glyphModel({
    id,
    principal: amount ?? 0n,
    startTime: now,
    unlockTime: now + lock,
    activeMultiplierBps: pool.multiplierBps,
    nowSeconds: now,
  });
  const lockDays = lock / 86_400n;
  const lockLine = lock === 0n ? "NO LOCK" : `DAY 0 / ${lockDays > 0n ? lockDays.toString() : "<1"}`;

  return (
    <div className="border border-ink bg-paper p-5">
      <div className="flex items-center justify-between gap-2">
        <p className="label">Position NFT · preview</p>
        <span className="tag border-ink-3 text-ink-3">Not minted</span>
      </div>

      <svg
        viewBox="0 0 400 400"
        role="img"
        aria-label={`Preview of position ${expectedId ? `#${expectedId}` : ""} in ${pool.name}: ${formatLockDuration(lock)} lock, ${formatMultiplier(pool.multiplierBps)} multiplier`}
        className="my-4 block h-auto w-full border border-ink"
        style={{ fontFamily: MONO }}
      >
        <rect width="400" height="400" fill={IVORY} />
        <g fill={INK}>
          <text x="24" y="36" fontSize="11" letterSpacing="2">
            FORMA / POSITION
          </text>
          <text x="376" y="40" fontSize="26" fontWeight="700" textAnchor="end">
            #{expectedId ? expectedId.toString() : "—"}
          </text>
          <text x="24" y="62" fontSize="15" fontWeight="700" letterSpacing="1">
            {pool.name.toUpperCase()}
          </text>
        </g>
        <line x1="24" y1="76" x2="376" y2="76" stroke={INK} strokeWidth="1" />
        <g transform="translate(200 196)">
          <GlyphMarks model={g} />
        </g>
        <text x="200" y="203" fontSize="20" fontWeight="700" fill={IVORY} textAnchor="middle">
          {formatMultiplier(pool.multiplierBps)}
        </text>
        <line x1="24" y1="324" x2="376" y2="324" stroke={INK} strokeWidth="1" />
        <g fill={INK} fontSize="11">
          <text x="24" y="346">
            PRINCIPAL
          </text>
          <text x="376" y="346" textAnchor="end">
            {amount !== undefined ? `${formatToken(amount)} FORGE` : "— FORGE"}
          </text>
          <text x="24" y="364">
            {lockLine}
          </text>
          <text x="376" y="364" textAnchor="end">
            {lock === 0n ? "OPEN" : "LOCKED"}
          </text>
          <text x="24" y="386" fontSize="9" letterSpacing="1.5" fillOpacity=".6">
            BASE SEPOLIA · TESTNET · NO MONETARY VALUE
          </text>
        </g>
      </svg>

      <dl className="mono text-xs">
        {(
          [
            ["Pool", pool.name],
            ["Lock", formatLockDuration(lock)],
            ["Multiplier", `${formatMultiplier(pool.multiplierBps)} while locked`],
            ["Est. rewards", rewardState],
            ["Position", expectedId ? `#${expectedId} expected · final id assigned on-chain` : "id assigned on-chain"],
          ] as [string, ReactNode][]
        ).map(([k, v]) => (
          <div key={k} className="grid grid-cols-[88px_1fr] gap-3 border-b border-rule py-2 last:border-b-0">
            <dt className="text-ink-3 uppercase">{k}</dt>
            <dd className="text-right">{v}</dd>
          </div>
        ))}
      </dl>
      <p className="mt-3 text-[11px] leading-snug text-ink-3">
        Same layout and glyph formula as the on-chain renderer. The real NFT is generated by the contract after your
        stake confirms.
      </p>
    </div>
  );
}
