#!/usr/bin/env node
// Generates the single source of ABIs and deployment addresses for TypeScript consumers:
//   packages/sdk/src/generated/abis.ts          ← packages/contracts/out/*.json (forge build artifacts)
//   packages/config/src/generated/deployments.ts ← deployments/*.json (deploy script manifests)
// Never edit the generated files by hand.
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "packages/contracts/out");

const CONTRACTS = [
  ["ForgeToken", "forgeTokenAbi"],
  ["FormaStaking", "formaStakingAbi"],
  ["PositionNFT", "positionNftAbi"],
  ["PositionRenderer", "positionRendererAbi"],
  ["LiquidStakingVault", "liquidStakingVaultAbi"],
];

const header = (src) =>
  `// AUTO-GENERATED by scripts/export-abis.mjs from ${src}. Do not edit.\n/* eslint-disable */\n\n`;

// ─── ABIs ──────────────────────────────────────────────────────────────────
if (!existsSync(out)) {
  console.error("packages/contracts/out not found — run `pnpm build:contracts` first.");
  process.exit(1);
}
let abis = header("forge build artifacts");
for (const [name, exportName] of CONTRACTS) {
  const file = join(out, `${name}.sol`, `${name}.json`);
  const { abi } = JSON.parse(readFileSync(file, "utf8"));
  abis += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
const abiDir = join(root, "packages/sdk/src/generated");
mkdirSync(abiDir, { recursive: true });
writeFileSync(join(abiDir, "abis.ts"), abis);

// ─── deployments ───────────────────────────────────────────────────────────
const depDir = join(root, "deployments");
const manifests = existsSync(depDir)
  ? readdirSync(depDir)
      .filter((f) => f.endsWith(".json"))
      .map((f) => JSON.parse(readFileSync(join(depDir, f), "utf8")))
  : [];

const REQUIRED = ["ForgeToken", "FormaStaking", "PositionNFT", "PositionRenderer", "LiquidStakingVault"];
const byChain = {};
for (const m of manifests) {
  for (const key of REQUIRED) {
    if (!/^0x[0-9a-fA-F]{40}$/.test(m.contracts?.[key] ?? "")) {
      throw new Error(`deployments/${m.network}.json: missing or invalid address for ${key}`);
    }
  }
  byChain[m.chainId] = {
    network: m.network,
    chainId: m.chainId,
    version: m.version,
    deployedAt: Number(m.deployedAt),
    startBlock: Number(m.startBlock),
    contracts: m.contracts,
    roles: m.roles,
    transactions: m.transactions ?? {},
  };
}

let deployments = header("deployments/*.json");
deployments += `import type { DeploymentManifest } from "../types";\n\n`;
deployments += `export const deployments: Partial<Record<number, DeploymentManifest>> = ${JSON.stringify(byChain, null, 2)};\n`;
const cfgDir = join(root, "packages/config/src/generated");
mkdirSync(cfgDir, { recursive: true });
writeFileSync(join(cfgDir, "deployments.ts"), deployments);

console.log(
  `ABIs: ${CONTRACTS.length} contracts → packages/sdk/src/generated/abis.ts\n` +
    `Deployments: ${Object.keys(byChain).join(", ") || "(none)"} → packages/config/src/generated/deployments.ts`,
);
